In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("Amazon.csv")

In [4]:
df.head()

,Unnamed: 0,Title,ratings,total_reviews,buying_history,alinknormal_URL,Price,Image
0,0,Plant-Based Kitchen Sponges - FSC Certified an...,4.6,248,3K+ bought in past month,https://www.amazon.com/Isshah-Plant-Based-Kitc...,9.99,https://m.media-amazon.com/images/I/81GEZUgvk2...
1,1,Reusable Paper Towels Washable Roll - Thick 12...,4.6,205,100+ bought in past month,https://www.amazon.com/EcoPledge-Reusable-Pape...,24.99,https://m.media-amazon.com/images/I/91-W1NYNeY...
2,2,20 Pack Reusable Paper Towels Washable - Natur...,4.4,3274,900+ bought in past month,https://www.amazon.com/Reusable-Alternative-Wa...,31.94,https://m.media-amazon.com/images/I/81WV3GCPce...
3,3,Akeeko Reusable Beeswax Food Wraps - Assorted ...,4.4,2426,50+ bought in past month,https://www.amazon.com/Reusable-Wraps-Beeswax-...,13.99,https://m.media-amazon.com/images/I/91UpDUvsk-...
4,4,Swedish Dishcloths for Kitchen Dish Towels - 6...,4.6,1286,100+ bought in past month,https://www.amazon.com/Harps-Seb-Reusable-Swed...,13.90,https://m.media-amazon.com/images/I/91FngmRdt1...

In [5]:
df.shape

(661, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 661 entries, 0 to 660
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       661 non-null    int64
 1   Title            661 non-null    object
 2   ratings          661 non-null    float64
 3   total_reviews    661 non-null    int64
 4   buying_history   661 non-null    object
 5   alinknormal_URL  661 non-null    object
 6   Price            661 non-null    float64
 7   Image            661 non-null    object
dtypes: float64(2), int64(2), object(4)
memory usage: 41.4+ KB

In [7]:
df.isnull().sum()

Unnamed: 0         0
Title              0
ratings            0
total_reviews      0
buying_history     0
alinknormal_URL    0
Price              0
Image              0
dtype: int64

In [8]:
df.describe()

       Unnamed: 0     ratings  total_reviews       Price
count  661.000000  661.000000     661.000000  661.000000
mean   339.750378    4.445840    3121.658094   20.121936
std    199.093262    0.284555    7155.038683   18.118538
min      0.000000    2.000000       1.000000    1.970000
25%    167.000000    4.300000     110.000000   12.690000
50%    339.000000    4.500000     543.000000   16.990000
75%    507.000000    4.600000    2886.000000   23.980000
max    693.000000    5.000000   94406.000000  289.990000

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

Unnamed: 0           int64
Title               object
ratings            float64
total_reviews        int64
buying_history      object
alinknormal_URL     object
Price              float64
Image               object
dtype: object

In [11]:
df.drop(columns=['Unnamed: 0'], inplace = True)

In [12]:
df.columns

Index(['Title', 'ratings', 'total_reviews', 'buying_history',
       'alinknormal_URL', 'Price', 'Image'],
      dtype='object')

In [13]:
(df['Title'].str.strip() == "").sum()

np.int64(0)

In [14]:
import re

repeated_word_titles = df[
    df["Title"].str.contains(
        r'\b(\w+)\s+\1\b',
        case=False,
        regex=True,
        na=False
    )
]

repeated_word_titles[["Title"]].head(20)

                                                 Title
472  Joob Joob Boho Pants for Women - Hippie Harem ...
588  Burt's Bees Baby Baby Boys Pajamas, 2-Piece Lo...

In [15]:
import re

def remove_repeated_words(text):
    if pd.isna(text):
        return text
    return re.sub(r'\b(\w+)(\s+\1\b)+', r'\1', text, flags=re.IGNORECASE)

df["Title"] = df["Title"].apply(remove_repeated_words)

In [16]:
df['Title']

0      Plant-Based Kitchen Sponges - FSC Certified an...
1      Reusable Paper Towels Washable Roll - Thick 12...
2      20 Pack Reusable Paper Towels Washable - Natur...
3      Akeeko Reusable Beeswax Food Wraps - Assorted ...
4      Swedish Dishcloths for Kitchen Dish Towels - 6...
                             ...
656                           PUMA Mens Club 5v5 Sneaker
657    DREAM PAIRS Women's Loafers Slip On Comfortabl...
658         Dr. Scholl's Shoes Women's Bianca Ankle Boot
659    HOBIBEAR Barefoot Minimalist Shoes Womens Mens...
660    Steel Toe Shoes for Men Women Comfortable Ligh...
Name: Title, Length: 661, dtype: object

In [17]:
for col in df.select_dtypes(include='object').columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().head(10))

--- Title ---
Title
Reusable Beeswax Wrap - 9 Pack Beeswax Wraps For Food, Organic, Sustainable, Biodegradable, Zero Waste, Plastic-Free Food Storage, 1L Strawberry, 3M Orange, 5S Lemon Patterns                            6
Tieralia 5-Piece Eco-Friendly Bamboo Dish Brush Set with Compostable Wood Pulp Sponges | Bamboo Kitchen Cleaning Set                                                                                      6
Plant-Based Kitchen Sponges - FSC Certified and PETA Approved, Natural, Eco-Friendly, Biodegradable Sisal Hemp Sponges for Dishes, Cleaning Sponge for Kitchen, Bathroom, Household - 12 Count            6
Bamboo Cutting Board, Durable Wood Cutting Boards for Kitchen with Deep Juice Grooves & Built-in Handles, Ideal Charcuterie & Chopping for Meat, Vegetables - Perfect Kitchen Gift for Home Cooks         5
Natural Kitchen Sponge - Biodegradable Compostable Cellulose and Coconut Scrubber Sponge - Pack of 12 Eco Friendly Sponges for Dishes                                                                     5
Zero Waste Natural Dish Soap Bar (Pack of 3 Bars) - Solid Vegan Dishwashing Block - Cold Processed, Eco Friendly Plastic Free Packaging with Sustainable Organic Ingredients for Kitchen                  4
| Premium Natural Kitchen Sponge | Non Scratch | Long Lasting | Waste Free | Compostable Sponge Kitchen | Natural Fiber | Eco-Friendly | Eartch Friendly | Vegan | 6 Pack                                 4
UNNI Compostable Liner Bags, 2.6 Gallon, 9.84 Liter, Extra Thick 0.71 Mil, 100 Count, Small Kitchen Food Scrap Waste Bags, ASTM D6400, US BPI, CMA and Europe OK compost HOME Certified, San Francisco    4
20 Pack Reusable Paper Towels Washable - Nature Friendly - Organic Cotton Alternative - Thick, Strong, Paperless Kitchen Dish Cloths - Reusable Napkins - Dish Towels - Cloth Napkin - Kitchen Towels     3
Akeeko Reusable Beeswax Food Wraps - Assorted 9 Packs, Eco-Friendly Reusable Wrap, Biodegradable, Zero Waste, Organic Cloth, Sustainable, Plastic-Free Food Storage, 1Large, 3Medium, 5Small Sizes        3
Name: count, dtype: int64

--- buying_history ---
buying_history
50+ bought in past month     288
1K+ bought in past month      61
100+ bought in past month     52
200+ bought in past month     44
2K+ bought in past month      28
500+ bought in past month     26
300+ bought in past month     22
4K+ bought in past month      20
10K+ bought in past month     20
600+ bought in past month     18
Name: count, dtype: int64

--- alinknormal_URL ---
alinknormal_URL
https://www.amazon.com/s?k=sustainable+clothing#              12
https://www.amazon.com/s?k=eco+friendly+fashion#              12
https://www.amazon.com/s?k=organic+cotton+clothing#           12
https://www.amazon.com/s?k=sustainable+home+goods#            10
https://www.amazon.com/s?k=bamboo+home+products#              10
https://www.amazon.com/s?k=sustainable+kitchen+products#       9
https://www.amazon.com/s?k=compostable+home+products#          9
https://www.amazon.com/s?k=biodegradable+kitchen+products#     9
https://www.amazon.com/s?k=zero+waste+kitchen#                 9
https://www.amazon.com/s?k=plastic+free+kitchen#               9
Name: count, dtype: int64

--- Image ---
Image
https://m.media-amazon.com/images/I/910pb+R-1UL._AC_UL320_.jpg    7
https://m.media-amazon.com/images/I/81GEZUgvk2L._AC_UL320_.jpg    6
https://m.media-amazon.com/images/I/81-cLbynG7L._AC_UL320_.jpg    6
https://m.media-amazon.com/images/I/81rF0i715fL._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/71g+Afy5T9L._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/91zidZ1V1VL._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/91UpDUvsk-L._AC_UL320_.jpg    4
https://m.media-amazon.com/images/I/71ybUvPV3nL._AC_UL320_.jpg    4
https://m.media-amazon.com/images/I/713GeQ-ieZL._AC_UL320_.jpg    4
https://m.media-amazon.com/images/I/71AC1L+FAwL._AC_UL320_.jpg    3
Name: count, dtype: int64

In [18]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ratings,661.0,4.445840,0.284555,2.00,4.30,4.50,4.60,5.00
total_reviews,661.0,3121.658094,7155.038683,1.00,110.00,543.00,2886.00,94406.00
Price,661.0,20.121936,18.118538,1.97,12.69,16.99,23.98,289.99

In [24]:
df.to_csv('cleaned_amazon.csv', index = False)

In [21]:
df.columns

Index(['Title', 'ratings', 'total_reviews', 'buying_history',
       'alinknormal_URL', 'Price', 'Image'],
      dtype='object')

In [22]:
print("Rating:", df["ratings"].min(), "to", df["ratings"].max())
print("Reviews:", df["total_reviews"].min(), "to", df["total_reviews"].max())
print("Price:", df["Price"].min(), "to", df["Price"].max())

Rating: 2.0 to 5.0
Reviews: 1 to 94406
Price: 1.97 to 289.99